### ISSUE TITLE
Angular renderer for dynamic components

### ISSUE THREAD

**Issue by dkrusenstrahle** [sibiraj-s/ngx-tiptap#2]
It would be fantastic if it was possible to render dynamic Angular components into the editor. Perhaps an Angular clone of the official VueRenderer or ReactRenderer.

**Comment by sibiraj-s** [comment]
@dkrusenstrahle I am able to make it work.


https://user-images.githubusercontent.com/20282546/116850859-01d2a100-ac0f-11eb-997c-562caf4a0041.mov

I will publish this today or tomorrow after some cleanup and added test cases.

**Comment by dkrusenstrahle** [comment]
@sibiraj-s Wow, great work! Really looking forward to try it out.

**Comment by dkrusenstrahle** [comment]
@sibiraj-s I can see that you have released the renderer super cool! However I cannot access it even if I reinstall or update ngx-tiptap. Any idea why? Is there a delay?

**Comment by dkrusenstrahle** [comment]
@sibiraj-s I extracted the file for now until the package is updated (worked perfectly). One thing comes into mind. I think the editor instance should be accessible within the dynamic component so that it can check if the editor is editable / activated or disabled in order to display different content for the user. Perhaps should the node instance it self also be accessible? What do you think?

**Comment by sibiraj-s** [comment]
Fixed in v1.2.0.  All [these props](https://www.tiptap.dev/guide/node-views/react#all-available-props) are now made available

**Comment by sibiraj-s** [comment]
> One thing comes into mind. I think the editor instance should be accessible within the dynamic component so that it can check if the editor is editable / activated or disabled in order to display different content for the user. Perhaps should the node instance it self also be accessible? What do you think?

These things I didn't add at first. I was slowly making changes and progressively pushing it to master. All these should be available now. I pushed all changes to master to fasten up the development, hence the confusion.

**Comment by dkrusenstrahle** [comment]
Perfect! I cannot get the Angular Node view redererer to work with 1.2.0. I get this error. I have reinstalled the package and restarted the server.

Module '"ngx-tiptap"' has no exported member 'AngularNodeViewRenderer'

**Comment by sibiraj-s** [comment]
Let me check.

**Comment by dkrusenstrahle** [comment]
Nevermind got it to work now. Saw there was some changes for updatesAttributes I had to fix. I reinstalled a few times and now it works.

**Comment by sibiraj-s** [comment]
Could be cache. Sometimes it takes small time to reflect after publishing the package.
