### ISSUE TITLE
No content displayed when it is JSON 

### ISSUE THREAD

**Issue by GitHubish** [sibiraj-s/ngx-tiptap#21]
Hello, while updating Tiptap and ngx tiptap I noticed a bug. When the editor is initialized and the input is in JSON no content is displayed. However there is no error. I could reproduce my case on this example: 

[stackblitz demo](https://stackblitz.com/edit/ngx-tiptap-etf4iy?file=src%2Fapp%2Fapp.component.ts)

**Comment by sibiraj-s** [comment]
I was able to see the content displayed in the editor correctly with JSON input in the stackblitz demo shared

<img width="458" alt="Screenshot 2022-01-18 at 7 04 20 AM" src="https://user-images.githubusercontent.com/20282546/149855593-cb99d595-be25-4fea-9001-daade3a90666.png">

**Comment by GitHubish** [comment]
@sibiraj-s Sorry my fork was not saved when Angular was upgraded to version 13. I just checked the demo is in v13 and the problem is clearly visible (chrome / brave and Firefox). On your side too? 

Thanks for your answer !

[demo](https://stackblitz.com/edit/ngx-tiptap-jddmxt?file=src%2Fapp%2Fapp.component.ts)

**Comment by sibiraj-s** [comment]
Can see the bug now. It was broken in 4.0.1 while fixing another bug.

**Comment by sibiraj-s** [comment]
Fixed in v4.0.4
