### ISSUE TITLE
TypeError: Cannot read property 'matchesNode' of null

### ISSUE THREAD

**Issue by wolfplus** [sibiraj-s/ngx-tiptap#25]
Hello, i found that this error is trigerrd when you destroy then you create the editor. It seems to have been solved in other farmework like react etc, but i guess in angular is not fixed yet

**Comment by sibiraj-s** [comment]
Could you provide a reproducible code for this? may be a stackblitz?

**Comment by sibiraj-s** [comment]
This issue is because the component itself destroys the editor on unmount. Fix would be a breaking change.

**Comment by sibiraj-s** [comment]
Should be fixed in v5. 

Note: Editor must be manually destroyed.
