### ISSUE TITLE
Angular 15 Support

### ISSUE THREAD

**Issue by Destreyf** [sibiraj-s/ngx-tiptap#30]
Angular 15 released recently, If possible it would be nice to see an angular 15 compatible release.

**Comment by sibiraj-s** [comment]
Hi @Destreyf . The current build should be compatible with angular 15. Are you facing any errors?

**Comment by Destreyf** [comment]
I cannot install due to the package.json dependencies tying it to angular
14.

**Comment by Destreyf** [comment]
At least that's the error I got earlier today, I'll be back at my computer in 8 to 10 hours and i will double check

**Comment by sibiraj-s** [comment]
Yes. It should support any version greater than 14. See https://github.com/sibiraj-s/ngx-tiptap/blob/master/projects/ngx-tiptap/package.json#L18. 

If there is something else please share the error. Will try to make a release.

**Comment by Destreyf** [comment]
I have done some additional testing, it appears it should work, we had some other dependencies conflicting that are causing us to delay our migration but as @sibiraj-s stated, it should be compatible, I believe we had a slightly older version at the time we originally tried to upgrade.

Part of the confusion on this is that we use NX internally and it didn't complain about any dependency issues in it's migrations, but once we tried to reinstall at a later time a bunch of packages were broken, this was one of them but it no longer complains about ngx-tiptap so I'm going to close this.

**Comment by sibiraj-s** [comment]
Thanks for the update @Destreyf
