### ISSUE TITLE
Support NodeViewWrapper, NodeViewContent, nodeViewProps

### ISSUE THREAD

**Issue by dkrusenstrahle** [sibiraj-s/ngx-tiptap#4]
Hello,

In this guide at the Tiptap documentation they show how to use content editable in a custom view node. But these files seems to be missing in this library.

These are the files that Vue uses:

`import { NodeViewWrapper, NodeViewContent, nodeViewProps } from '@tiptap/vue-2'`

This is the documentation page:

`https://www.tiptap.dev/guide/node-views/vue`

Is there already supported in Ngx-tiptap?

Thanks!

**Comment by sibiraj-s** [comment]
Hey yes. It is supported already. I won't be able till tomorrow.can you check the demo folder for the steps. See here https://github.com/sibiraj-s/ngx-tiptap/blob/master/projects/demo/src/app/extensions.ts

**Comment by sibiraj-s** [comment]
Were you able to find it?

**Comment by dkrusenstrahle** [comment]
Yes, your example worked! I am just trying to figure out how not to create a new node when hitting enter now :)

Thanks!

**Comment by sibiraj-s** [comment]
Cool. I will leave this issue open until I add the doc.

**Comment by sibiraj-s** [comment]
Added to README. You can now use the `tiptapNodeViewContent` directive instead of the attribute.

**Comment by gethari** [comment]
Hi @sibiraj-s I could'nt able to find `NodeViewWrapper`. Sorry I am not able to fully understand the tiptap's vue part of the code
