### ISSUE TITLE
Docs Improvement: Suggest ::ng-deep instead of ViewEncapsulation

### ISSUE THREAD

**Issue by Routhinator** [sibiraj-s/ngx-tiptap#43]
Hey there,

ViewEncapsulation has some broad reaching implications, however styles can be overridden in the `tiptap-editor` component with `::ng-deep` which is more focused and safer. For example, to kill off the focus outline on nodes:

```
:host ::ng-deep .ProseMirror {
  &:focus {
    outline: none;
  }
  &:focus-visible {
    outline: none;
  }
}
```

**Comment by sibiraj-s** [comment]
Those are getting deprecated. Don't want to suggest that.

https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

Open to alternate options

**Comment by Routhinator** [comment]
They aren't though, it's complicated. Angular is flagging them due to WC3 deprecating /deep/ - but Angular has no plans to remove `::ng-deep` - in fact theres a follow up proposal introduced to keep these features around. 

Discussion here, along with the link to the WC3 draft proposal Google has submitted https://stackoverflow.com/questions/47024236/what-to-use-in-place-of-ng-deep

**Comment by Routhinator** [comment]
Complex nest of stuff here, TL;DR is that in 2023 `ng-deep` is still the safest option, but looks like Angular devs are going this way:

from https://github.com/angular/angular/issues/25160#issuecomment-979222243 

> CSS Variables open the door to well-supported APIs for component customization, allowing developers to shift away from CSS overrides and ::ng-deep.
> 
> We recommend introducing custom variables in your libraries and dependencies in order to create an API surface for customizing libraries without the need for ::ng-deep. Implementation of custom variables allows developers to have more control over their styling and provide a path away from CSS overrides and ::ng-deep.

...basically saying that libraries need to add custom variables so we can override styles within them like the outline issue I put in my snippet above.

**Comment by sibiraj-s** [comment]
Thanks for the suggestion. I've updated the in README now, but it has both the steps, as the preference is upto the user on what method to choose.
