### ISSUE TITLE
[Question] slash command

### ISSUE THREAD

**Issue by sp90** [sibiraj-s/ngx-tiptap#44]
Hi

I was wondering do anyone here have an angular package for slash command?

**Comment by sibiraj-s** [comment]
You don't need an angular package for that. You need to implement a tiptap extension. 

You can follow some reference here https://tiptap.dev/experiments/commands.

Closing as this is not an issue with the editor.

**Comment by sp90** [comment]
Yes while i know that; the example inject vue and or react rendered components which are kind of a different approach 

So just wondered how other angular devs goes about that

**Comment by sibiraj-s** [comment]
Please create a discussion. Thanks
