### ISSUE TITLE
applicationRef.injector vs hierarchical injector in AngularRenderer

### ISSUE THREAD

**Issue by Benny739** [sibiraj-s/ngx-tiptap#56]
Hi,

is there a reason why you used the applicationRef.injector and not the passed hierarchical injector for the component in the AngularRenderer? 
This way we can't pass any hierarchical injection data to the component.

**Comment by sibiraj-s** [comment]
To be honest, I don't remember why. Its been a while. I am open to better suggestions/fix.

**Comment by Benny739** [comment]
I propose to switch the injector to the passed injector. This way the consumer can decide which injector to pass and take advantage of the hierarchical injector, e.g. the consumer can dynamically override providers when needed.

If you're fine with that I can create a PR.

**Comment by sibiraj-s** [comment]
Sure, Thanks. We can do that. will it be a breaking change though?

**Comment by nikes** [comment]
@Benny739 what's your progress on that?

**Comment by Benny739** [comment]
@sibiraj-s if someone accidentally overwrote some dependencies, it could be a breaking change, because all dependency come from the root injector atm.

@nikes the change is very small, I can test and open a PR in the next few days.

**Comment by nikes** [comment]
@Benny739 Oh it would be cool to see your PR, I have some thoughts on that too, so I want to wait for your PR, maybe they will be similar =)

**Comment by sibiraj-s** [comment]
Sure.

**Comment by Benny739** [comment]
PR is opened #59

**Comment by sibiraj-s** [comment]
Published in v9.1.0. Thanks @Benny739
