### ISSUE TITLE
Editor selected node doesn't update with onPush change detection.

### ISSUE THREAD

**Issue by tutkli** [sibiraj-s/ngx-tiptap#61]
When using `changeDetection: ChangeDetectionStrategy.OnPush`, the component doesn't get notified when the selected node changes, braking tool buttons reactivity.

Stackblitz with reproduction: https://stackblitz.com/edit/stackblitz-starters-zv63i5?file=src%2Fmain.ts

In the demo, `app-menu` component has OnPush CD.
1. Toggle some text to bold or italic. The button will apply their active class.
2. Change cursor position. The tool button remains active.

Only workaround is removing all OnPush CD all the way to the root component, which could worse the app performance.

**Comment by sibiraj-s** [comment]
Available in v9.1.1
