### ISSUE TITLE
Problem with compilation when running Angular v17 SSR

### ISSUE THREAD

**Issue by Figments** [sibiraj-s/ngx-tiptap#64]
hello!

i've been trying to get this package working with Angular 17 with SSR enabled (a requirement for my needs), but adding `NgxTiptapModule` to `importProvidersFrom` in the app config leads to the following errors:

```
12:16:42 PM [vite] Error when evaluating SSR module /main.server.mjs:
|- SyntaxError: Unexpected token ':'
    at new AsyncFunction (<anonymous>)
    at instantiateModule 

12:16:42 PM [vite] Internal server error: Unexpected token ':'
      at new AsyncFunction (<anonymous>)
      at instantiateModule 
```
removing `NgxTiptapModule` from the `importProvidersFrom` function restores proper compilation. this is also true if i import `NgxTiptapModule` directly in the `imports` array of any standalone component—the moment said component gets used, the entire app stops compiling and produces the same errors.

i've also tried removing all of the `@tiptap/*` packages i've installed and recompiling with *just* `ngx-tiptap`, but it only ever produces the same issue.

**Comment by sibiraj-s** [comment]
This module is not tested with SSR and also `titptap/prosemirror` is not an SSR supported module, its a pure client library. You should lazy load the editor in client

**Comment by sibiraj-s** [comment]
Closing this, since the component needs to be lazily loaded on a server component, or mark the route as client only route and not use it directly.
