### ISSUE TITLE
Upgrade to Angular 18

### ISSUE THREAD

**Issue by CharlieGreenman** [sibiraj-s/ngx-tiptap#67]
Angular 18 is now available

**Comment by CharlieGreenman** [comment]
@sibiraj-s made a pull request here for Angular 18 https://github.com/sibiraj-s/ngx-tiptap/pull/68

**Comment by CharlieGreenman** [comment]
I created an 18 version here in the meantime: https://www.npmjs.com/package/@razroo/ngx-tiptap

**Comment by sibiraj-s** [comment]
Sorry. I forgot to get back on this. Will get it deployed today.

**Comment by sibiraj-s** [comment]
Published in v11.0.0
