### ISSUE TITLE
Cannot display tiptapNodeViewContent when editor is disabled

### ISSUE THREAD

**Issue by dkrusenstrahle** [sibiraj-s/ngx-tiptap#7]
Hello @sibiraj-s!

I have created a custom node view that is editable (using tiptapNodeViewContent).
It works very good but I have one issue. How can I show the data from the editble field when viewing the editor in none editable state (editor is not in editable mode).

Using this does not output the content of the editable field.

<div tiptapNodeViewContent></div>

Strange thing is if I click into the editor area it appears. So tiptapNodeViewContent is only filled when clicking on it.

**Comment by dkrusenstrahle** [comment]
@sibiraj-s An update. I have to click on the div that contains (should contain) the content.
I have removed all HTML markup and CSS to make sure it's not impacting.

Before click:

`<div tiptapnodeviewcontent="" data-node-view-content=""></div>`

After click:

```
<div tiptapnodeviewcontent="" data-node-view-content="">
    <div style="white-space: inherit;"><p>TEST</p></div>
 </div>
```

**Comment by sibiraj-s** [comment]
is this a regression? used to work before the directive? i.e., with `data-node-view-content` attribute?

**Comment by sibiraj-s** [comment]
Fixed in v1.4.1

**Comment by sibiraj-s** [comment]
Github actions is down at the moment https://www.githubstatus.com/incidents/zbpwygxwb3gw. New version will be published once the action services are up.

**Comment by sibiraj-s** [comment]
Published.
