### ISSUE TITLE
Not working with ANGULAR 17

### ISSUE THREAD

**Issue by grim-reapper** [sibiraj-s/ngx-tiptap#72]
This is not rendering content in angular v17 with standalone component

**Comment by sibiraj-s** [comment]
This package is not standalone ready yet. There is a open PR https://github.com/sibiraj-s/ngx-tiptap/pull/70. If thats not the case, kindly provide more info.

**Comment by bboyle** [comment]
You can use it inside a standalone component by importing the module. I've had to do this with all the material components too

```ts
@Component({
  selector: 'my-custom-component',
  standalone: true,
  imports: [NgxTiptapModule],
…
```

**Comment by sibiraj-s** [comment]
Yeah, I would suggest importing module inside components like @bboyle . Standalone will be supported in next major.
