### ISSUE TITLE
Cannot find module '@tiptap/starter-kit' or its corresponding type declarations.

### ISSUE THREAD

**Issue by swethadmurthy** [sibiraj-s/ngx-tiptap#74]
Hi Team, I'm trying to use "ngx-tiptap@10.0.0" , as latest version is not supported for Angular 17, but I'm getting below error with starter-kit. Please let me know if I should be using any other module.

Cannot find module '@tiptap/starter-kit' or its corresponding type declarations.

**Comment by sibiraj-s** [comment]
What package manager are you using, sometimes you need to install peerDependencies manually if your package manager doesn't automatically.

**Comment by suplakite** [comment]
Have same issue - npm i ngx-tiptap@10.1.0  for angular 17.
npm vesrion: 10.2.4
There is no @tiptap/starter-kit installed

**Comment by bboyle** [comment]
saw the same. starter-kit is a tiptap extension tho, so it makes sense to install it separately if you want it (maybe some people don't want/need it if they are customising tiptap in different ways). could be good to update the readme about this?

https://tiptap.dev/docs/editor/extensions/functionality/starterkit

**Comment by sibiraj-s** [comment]
my bad, just realized 🤔 starterkit is not a dependency of this project. i got mixed up with another project which I had.

If you need starter kit, you'll need to install it yourself.

If you had snippets copied from README. Those are just examples, not part of package.
