### ISSUE TITLE
Editable: False is not working!

### ISSUE THREAD

**Issue by thehaseebahmed** [sibiraj-s/ngx-tiptap#75]
It is pretty self explanatory. I have no idea why but passing in the following configuration does not disable tiptap from being editable.

```
constructor() {
    this.editor = new Editor({
      editable: false,
      editorProps: {
        attributes: {
          class: 'focus:outline-none',
        },
      },
      extensions: [StarterKit],
    });
  }
```

**Comment by sibiraj-s** [comment]
Currently its handled to directly use the angular forms api, so you can set the disabled state directly like you would do on an input element, probably that overrides this.

See https://github.com/sibiraj-s/ngx-tiptap/blob/master/projects/ngx-tiptap/src/lib/editor.directive.ts#L51

**Comment by thehaseebahmed** [comment]
Thanks! I figured that out yesterday so apologies for this issue.
